name: Deploy to surge

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: 12

    - name: Build Angular App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings

    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./dist/angular-export-excel https://angular-export-excel.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
